### ISSUE TITLE
File parsing error

### ISSUE THREAD

**Issue by m4xwellNo4h** [NHERI-SimCenter/CFDClientProgram#93]
![screen shot 2017-09-19 at 5 28 00 pm](https://user-images.githubusercontent.com/6550528/30675901-2143c5a2-9e38-11e7-84e9-cefcede000b2.png)

After login on most recent version 9/20/17
Mac El Capitan 10.11.6

**Comment by psempoli** [comment]
This was a problem with Max's underlying account.
